"""Train a custom, from-scratch int8 TinyML classifier for “Hey Captain”.

The exported classifier consumes the same 49x40 int8 micro-features used by
TensorFlow Lite Micro's micro_speech frontend. No globally pre-trained keyword
weights are downloaded or used.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import random
import wave
from pathlib import Path

os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")
import numpy as np
import tensorflow as tf

ROOT = Path(__file__).parent
CONFIG = json.loads((ROOT / "config.json").read_text(encoding="utf-8"))
LABELS = CONFIG["labels"]
RATE = CONFIG["sampleRateHz"]
CLIP_SAMPLES = RATE * CONFIG["clipMs"] // 1000


def load_pcm(path: Path) -> np.ndarray:
    with wave.open(str(path), "rb") as source:
        if source.getnchannels() != 1 or source.getsampwidth() != 2 or source.getframerate() != RATE:
            raise ValueError(f"{path}: expected mono, 16-bit PCM, {RATE} Hz")
        values = np.frombuffer(source.readframes(source.getnframes()), dtype="<i2")
    if values.size < CLIP_SAMPLES:
        values = np.pad(values, (0, CLIP_SAMPLES - values.size))
    elif values.size > CLIP_SAMPLES:
        start = (values.size - CLIP_SAMPLES) // 2
        values = values[start:start + CLIP_SAMPLES]
    return values.astype(np.int16)


def micro_features(pcm: np.ndarray) -> np.ndarray:
    if not hasattr(tf.raw_ops, "AudioMicrofrontend"):
        raise RuntimeError("This TensorFlow build lacks AudioMicrofrontend. Use a TensorFlow CPU wheel that includes the speech microfrontend op.")
    features = tf.raw_ops.AudioMicrofrontend(
        audio=tf.convert_to_tensor(pcm, tf.int16), sample_rate=RATE,
        window_size=CONFIG["windowMs"], window_step=CONFIG["strideMs"],
        num_channels=CONFIG["featureBins"], upper_band_limit=7500.0,
        lower_band_limit=125.0, enable_pcan=True,
    )
    # Matches the integer rescaling documented by TFLM micro_speech.
    values = features.numpy().astype(np.int32)
    values = ((values * 256 + 333) // 666) - 128
    values = np.clip(values, -128, 127).astype(np.int8)
    expected = (49, CONFIG["featureBins"])
    if values.shape != expected:
        raise RuntimeError(f"Frontend produced {values.shape}; expected {expected}. Training and firmware frontend must match.")
    return values[..., None]


def collect(dataset: Path) -> tuple[np.ndarray, np.ndarray, list[str]]:
    files: list[tuple[Path, int]] = []
    for label_index, label in enumerate(LABELS):
        if label == "silence":
            continue
        files.extend((path, label_index) for path in sorted((dataset / label).glob("*.wav")))
    backgrounds = sorted((dataset / "background").glob("*.wav"))
    if len(list((dataset / "hey_captain").glob("*.wav"))) < 100:
        raise RuntimeError("Need at least 100 genuine 'hey captain' clips. Capture multiple speakers, rooms and distances.")
    if len(list((dataset / "unknown").glob("*.wav"))) < 100:
        raise RuntimeError("Need at least 100 unknown/non-keyword clips, including confusing phrases.")
    if not backgrounds:
        raise RuntimeError("Need background recordings for the silence class.")
    items: list[tuple[np.ndarray, int, str]] = []
    for path, label in files:
        items.append((micro_features(load_pcm(path)), label, str(path)))
    # Background clips form the explicit silence/no-wake class.
    target_silence = max(100, len(items) // 3)
    for index in range(target_silence):
        path = backgrounds[index % len(backgrounds)]
        items.append((micro_features(load_pcm(path)), LABELS.index("silence"), str(path)))
    random.Random(26171).shuffle(items)
    return np.stack([x[0] for x in items]), np.asarray([x[1] for x in items], np.int64), [x[2] for x in items]


def model() -> tf.keras.Model:
    inputs = tf.keras.Input((49, CONFIG["featureBins"], 1), dtype=tf.float32)
    x = tf.keras.layers.Conv2D(8, (10, 8), strides=(2, 2), activation="relu", padding="valid")(inputs)
    x = tf.keras.layers.Dropout(0.15)(x)
    x = tf.keras.layers.Flatten()(x)
    outputs = tf.keras.layers.Dense(len(LABELS), activation="softmax")(x)
    return tf.keras.Model(inputs, outputs, name="captain_tiny_conv")


def c_array(data: bytes) -> str:
    rows = [", ".join(f"0x{byte:02x}" for byte in data[i:i + 12]) for i in range(0, len(data), 12)]
    return "// Generated by kws/train.py; trained from the local custom dataset.\n#pragma once\n#include <cstdint>\n" + \
        f"alignas(16) const unsigned char g_captain_kws_model[] = {{\n  " + ",\n  ".join(rows) + \
        f"\n}};\nconst unsigned int g_captain_kws_model_len = {len(data)};\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", type=Path, default=ROOT / "dataset")
    parser.add_argument("--out", type=Path, default=ROOT / "artifacts")
    parser.add_argument("--epochs", type=int, default=35)
    args = parser.parse_args()
    tf.keras.utils.set_random_seed(26171)
    x, y, paths = collect(args.dataset)
    split = int(len(x) * 0.8)
    train_x, test_x = x[:split].astype(np.float32), x[split:].astype(np.float32)
    train_y, test_y = y[:split], y[split:]
    network = model()
    network.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
    network.fit(train_x, train_y, validation_split=0.15, epochs=args.epochs, batch_size=32,
                callbacks=[tf.keras.callbacks.EarlyStopping(patience=5, restore_best_weights=True)], verbose=2)
    loss, accuracy = network.evaluate(test_x, test_y, verbose=0)
    converter = tf.lite.TFLiteConverter.from_keras_model(network)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    converter.representative_dataset = lambda: ([sample[None, ...].astype(np.float32)] for sample in train_x[: min(300, len(train_x))])
    data = converter.convert()
    budget = CONFIG["budgets"]["modelBytes"]
    if len(data) > budget:
        raise RuntimeError(f"Quantized model is {len(data)} bytes; budget is {budget}")
    args.out.mkdir(parents=True, exist_ok=True)
    (args.out / "captain_kws_int8.tflite").write_bytes(data)
    (args.out / "captain_kws_model.h").write_text(c_array(data), encoding="utf-8")
    report = {
        "keyword": CONFIG["keyword"], "trainedFromScratch": True,
        "pretrainedKeywordWeights": False, "labels": LABELS,
        "datasetClips": len(paths), "heldOutClips": len(test_x),
        "heldOutAccuracy": float(accuracy), "heldOutLoss": float(loss),
        "modelBytes": len(data), "modelSha256": hashlib.sha256(data).hexdigest(),
        "physicalMetricsVerified": False,
    }
    (args.out / "training-report.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
